export const mockPrivileges = [
  "manage_batches",
  "view_reports",
  "start_session",
  "approve_assignments",
  "manage_courses",
  "view_students",
  "grade_assignments",
  "join_session",
  "view_own_progress",
]

export const mockTrainers = [
  {
    id: 1,
    photo: "/placeholder.svg?height=40&width=40",
    name: "furqan syed",
    gender: "Male",
    dob: "05-11-2024",
    phone: "222222222",
    email: "furqan@aiskool.com",
    institute: "Vrindavan -aiskool",
    status: "active",
    courses: 3,
    students: 45,
    privileges: ["manage_batches", "start_session", "view_reports", "view_students"],
  },
  {
    id: 2,
    photo: "/placeholder.svg?height=40&width=40",
    name: "Snehal s",
    gender: "Female",
    dob: "01-05-2025",
    phone: "8787888888",
    email: "snehal@aiskool.com",
    institute: "Vrindavan -aiskool",
    status: "active",
    courses: 2,
    students: 32,
    privileges: ["manage_batches", "start_session", "view_students"],
  },
  // Added John Smith for privilege management demo
  {
    id: 6,
    photo: "/placeholder.svg?height=40&width=40",
    name: "John Smith",
    gender: "Male",
    dob: "01-01-1980",
    phone: "9999999999",
    email: "trainer@eduflow.com",
    institute: "Demo Institute",
    status: "active",
    courses: 0,
    students: 0,
    privileges: ["manage_batches", "manage_courses", "view_students"],
  },
  {
    id: 3,
    photo: "/placeholder.svg?height=40&width=40",
    name: "Dummy trainer",
    gender: "Male",
    dob: "19-06-2001",
    phone: "1234567890",
    email: "dummy@gmail.com",
    institute: "Vrindavan -aiskool",
    status: "pending",
    courses: 1,
    students: 15,
    privileges: ["view_students"],
  },
  {
    id: 4,
    photo: "/placeholder.svg?height=40&width=40",
    name: "humanity trainer",
    gender: "Male",
    dob: "03-06-2025",
    phone: "7888888888",
    email: "humanitytrainer@aiskool.com",
    institute: "humanitypublicschool",
    status: "active",
    courses: 2,
    students: 28,
    privileges: ["manage_batches", "start_session", "approve_assignments"],
  },
  {
    id: 5,
    photo: "/placeholder.svg?height=40&width=40",
    name: "karim shaikh",
    gender: "Male",
    dob: "16-07-2025",
    phone: "565555555",
    email: "karim.shaikh@aiskool.com",
    institute: "humanitypublicschool",
    status: "active",
    privileges: ["manage_batches", "view_reports"],
  },
]

export const mockCoordinators = [
  {
    id: 1,
    photo: "/placeholder.svg?height=40&width=40",
    name: "Huma patel",
    gender: "Female",
    dob: "08-12-1987",
    phone: "9967478289",
    email: "humapatelai29@gmail.com",
    institute: "Vrindavan -aiskool",
    status: "active",
    privileges: ["manage_batches", "view_reports", "view_students"],
  },
  {
    id: 2,
    photo: "/placeholder.svg?height=40&width=40",
    name: "arif shaikh shaikh",
    gender: "Male",
    dob: "17-06-2025",
    phone: "8999999999",
    email: "humanityschool@gmail.com",
    institute: "humanitypublicschool",
    status: "active",
    privileges: ["manage_batches", "view_students"],
  },
]

export const mockStudents = [
  {
    id: 1,
    photo: "/placeholder.svg?height=40&width=40",
    name: "John Doe",
    status: "Verified",
    email: "john.doe@student.com",
    enrolledCourses: "Web Development, Python",
    school: "Vrindavan -aiskool",
    privileges: ["join_session", "view_own_progress"],
  },
  {
    id: 2,
    photo: "/placeholder.svg?height=40&width=40",
    name: "Jane Smith",
    status: "Verified",
    email: "jane.smith@student.com",
    enrolledCourses: "Data Science",
    school: "humanitypublicschool",
    privileges: ["join_session", "view_own_progress"],
  },
  {
    id: 3,
    photo: "/placeholder.svg?height=40&width=40",
    name: "Mike Johnson",
    status: "Unverified",
    email: "mike.johnson@student.com",
    enrolledCourses: "",
    school: "Vrindavan -aiskool",
    privileges: [],
  },
]

export const mockSchools = [
  {
    id: 1,
    logo: "/placeholder.svg?height=40&width=40",
    schoolName: "Vrindavan -aiskool",
    contactPerson: "Huma patel",
    email: "humapatelai29@gmail.com",
    phone: "9967478289",
    status: "active",
    students: 150,
    batches: 8,
  },
  {
    id: 2,
    logo: "/placeholder.svg?height=40&width=40",
    schoolName: "humanitypublicschool",
    contactPerson: "arif shaikh shaikh",
    email: "humanityschool@gmail.com",
    phone: "8999999999",
    status: "active",
    students: 200,
    batches: 12,
  },
]

export const mockBatches = [
  {
    id: 1,
    batchId: "AIS8070",
    batchName: "B1",
    trainer: "furqan syed",
    course: "Web Development",
    noOfStudents: 25,
    maxStudents: 30,
    status: "active",
    startDate: "2024-01-15",
  },
  {
    id: 2,
    batchId: "AIS3360",
    batchName: "summer workshop 25",
    trainer: "Snehal s",
    course: "ROBO SENIOR",
    noOfStudents: 2,
    maxStudents: 20,
    status: "active",
    startDate: "2024-02-01",
  },
  {
    id: 3,
    batchId: "AIS4412",
    batchName: "summer camp second",
    trainer: "furqan syed",
    course: "PROTON-BLOCKS",
    noOfStudents: 2,
    maxStudents: 25,
    status: "pending",
    startDate: "2024-02-15",
  },
  {
    id: 4,
    batchId: "AIS2182",
    batchName: "B123",
    trainer: "furqan syed",
    course: "PROTON-BLOCKS",
    noOfStudents: 3,
    maxStudents: 30,
    status: "active",
    startDate: "2024-01-20",
  },
  {
    id: 5,
    batchId: "AIS6742",
    batchName: "H1",
    trainer: "humanity trainer",
    course: "test final course",
    noOfStudents: 4,
    maxStudents: 25,
    status: "active",
    startDate: "2024-01-25",
  },
  {
    id: 6,
    batchId: "AIS7045",
    batchName: "H2",
    trainer: "karim shaikh",
    course: "test final course",
    noOfStudents: 4,
    maxStudents: 30,
    status: "completed",
    startDate: "2024-01-10",
  },
]

export const mockAssignments = [
  {
    id: 1,
    title: "Build Your First Website",
    batch: "Web Dev Batch 2024-A",
    course: "Web Development Fundamentals",
    dueDate: "2024-01-25",
    submissions: 12,
    maxScore: 100,
    status: "active",
    trainer: "furqan syed",
  },
  {
    id: 2,
    title: "Data Analysis Project",
    batch: "Data Science Batch 2024-A",
    course: "Data Science with Python",
    dueDate: "2024-02-15",
    submissions: 8,
    maxScore: 100,
    status: "active",
    trainer: "Snehal s",
  },
  {
    id: 3,
    title: "Marketing Campaign Analysis",
    batch: "Digital Marketing Batch 2024-A",
    course: "Digital Marketing Essentials",
    dueDate: "2024-01-30",
    submissions: 15,
    maxScore: 100,
    status: "completed",
    trainer: "humanity trainer",
  },
]

export const mockEnrollmentHistory = [
  {
    id: 1,
    photo: "/placeholder.svg?height=40&width=40",
    userName: "John Doe",
    email: "john.doe@student.com",
    enrolledCourse: "Web Development Fundamentals",
    enrollmentDate: "Tue, 01-Jul-2025",
    status: "active",
  },
  {
    id: 2,
    photo: "/placeholder.svg?height=40&width=40",
    userName: "Jane Smith",
    email: "jane.smith@student.com",
    enrolledCourse: "Data Science with Python",
    enrollmentDate: "Wed, 02-Jul-2025",
    status: "active",
  },
  {
    id: 3,
    photo: "/placeholder.svg?height=40&width=40",
    userName: "Mike Johnson",
    email: "mike.johnson@student.com",
    enrolledCourse: "Digital Marketing Essentials",
    enrollmentDate: "Thu, 03-Jul-2025",
    status: "pending",
  },
]

export const mockCourses = [
  {
    id: 1,
    title: "A-Tiny",
    instructor: "Aiskool Mumbai",
    category: "Beginner",
    totalSections: 3,
    totalLessons: 17,
    totalEnrollment: 14,
    status: "active",
    price: "Free",
    createdAt: "2024-01-15",
  },
  {
    id: 2,
    title: "PROTON-BLOCKS",
    instructor: "Aiskool Mumbai",
    category: "Beginner",
    totalSections: 4,
    totalLessons: 14,
    totalEnrollment: 21,
    status: "active",
    price: "Free",
    createdAt: "2024-01-20",
  },
  {
    id: 3,
    title: "SCRATCH-JUNIOR",
    instructor: "Aiskool Mumbai",
    category: "Beginner",
    totalSections: 4,
    totalLessons: 20,
    totalEnrollment: 13,
    status: "active",
    price: "Free",
    createdAt: "2024-01-25",
  },
  {
    id: 4,
    title: "PROTON BLOCK PLUS",
    instructor: "Aiskool Mumbai",
    category: "Beginner",
    totalSections: 0,
    totalLessons: 0,
    totalEnrollment: 4,
    status: "active",
    price: "₹5600",
    createdAt: "2024-02-01",
  },
]

export const mockSections = [
  {
    id: 1,
    title: "Getting Started With Mtiny",
    courseId: 1,
    order: 1,
    lessons: [
      { id: 1, title: "Introduction Of Robot", type: "document" },
      { id: 2, title: "Introduction Video", type: "video" },
      { id: 3, title: "Map Blocks", type: "document" },
      { id: 4, title: "Map Blocks Video", type: "video" },
    ],
    quizzes: [
      { id: 1, title: "test1" },
      { id: 2, title: "Section 1 Quiz" },
    ],
  },
  {
    id: 2,
    title: "Learning The Coding Tools",
    courseId: 1,
    order: 2,
    lessons: [],
    quizzes: [],
  },
  {
    id: 3,
    title: "Exploring Mtiny Features",
    courseId: 1,
    order: 3,
    lessons: [],
    quizzes: [],
  },
]
